### PR TITLE
More experiment with code cov tool

### PR DESCRIPTION
**Pull request by yitam**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/msphpsql/597)

### CODE REVIEW

**Comment by david-puglielli** [comment]
*[appveyor.yml, line 196 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/597#-Kz_YCpUm-aw5eHphIdR:-Kz_YCpUm-aw5eHphIdS:b-808y1q) ([raw file](https://github.com/microsoft/msphpsql/blob/3d674d88f736bd0936eaee4775d4e20d7debcf78/appveyor.yml#L196)):*
> ```YAML
>     # - type %APPVEYOR_BUILD_FOLDER%\test\functional\sqlsrv.log
>     # - php run-tests.php -p php.exe %APPVEYOR_BUILD_FOLDER%\test\functional\pdo_sqlsrv\*.phpt > %APPVEYOR_BUILD_FOLDER%\test\functional\pdo_sqlsrv.log 2>&1
>     # - type %APPVEYOR_BUILD_FOLDER%\test\functional\pdo_sqlsrv.log    - python %APPVEYOR_BUILD_FOLDER%\test\functional\setup\cleanup_dbs.py -dbname %SQLSRV_DBNAME%
> ```

I think you missed a new line here for the cleanup command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/597)*

**Comment by yitam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 196 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/597#-Kz_YCpUm-aw5eHphIdR:-Kz__C7VAM4raWESqR9s:bfo2mn5) ([raw file](https://github.com/microsoft/msphpsql/blob/3d674d88f736bd0936eaee4775d4e20d7debcf78/appveyor.yml#L196)):*
<details><summary><i>Previously, david-puglielli (David Puglielli) wrote…</i></summary><blockquote>

I think you missed a new line here for the cleanup command.
</blockquote></details>

right! thanks 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/597)*

**Comment by david-puglielli** [comment]
*[appveyor.yml, line 182 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/597#-Kz__Nl6foae6OFK_lov:-Kz__Nl6foae6OFK_low:b-kjm20q) ([raw file](https://github.com/microsoft/msphpsql/blob/3d674d88f736bd0936eaee4775d4e20d7debcf78/appveyor.yml#L182)):*
> ```YAML
>             Write-Host "Running phpt tests via OpenCppCoverage..."
>             $ext_dir = ${env:PHP_SDK_DIR} + "\php-" + ${env:PHP_VERSION} + "-src\ext";
>             OpenCppCoverage.exe --sources $ext_dir\sqlsrv --sources $ext_dir\pdo_sqlsrv --modules ext\php_sqlsrv.dll --modules ext\php_pdo_sqlsrv.dll --export_type=cobertura:.\coverage.xml  --quiet --cover_children --continue_after_cpp_exception --optimized_build -- php.exe run-tests.php -P ${env:APPVEYOR_BUILD_FOLDER}\test\functional\ | out-file -filePath ${env:APPVEYOR_BUILD_FOLDER}\test\functional\tests.log -encoding UTF8;
> ```

Are we sure this is the correct php.exe? There won't be any other php in the path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/597)*

**Comment by yitam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[appveyor.yml, line 182 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/597#-Kz__Nl6foae6OFK_lov:-Kz_aTdCHTUCv_isdQEH:b-v4y5uu) ([raw file](https://github.com/microsoft/msphpsql/blob/3d674d88f736bd0936eaee4775d4e20d7debcf78/appveyor.yml#L182)):*
<details><summary><i>Previously, david-puglielli (David Puglielli) wrote…</i></summary><blockquote>

Are we sure this is the correct php.exe? There won't be any other php in the path?
</blockquote></details>

I believe that's the php we compiled in %PHP_INSTALL_DIR% but I can use .\php.exe if you like

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/597)*

**Comment by david-puglielli** [comment]
*[appveyor.yml, line 182 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/597#-Kz__Nl6foae6OFK_lov:-Kz_jW1k68bKj-fMPSDG:b-k6n70r) ([raw file](https://github.com/microsoft/msphpsql/blob/3d674d88f736bd0936eaee4775d4e20d7debcf78/appveyor.yml#L182)):*
<details><summary><i>Previously, yitam (Jenny Tam) wrote…</i></summary><blockquote>

I believe that's the php we compiled in %PHP_INSTALL_DIR% but I can use .\php.exe if you like
</blockquote></details>

I think best to put in a .\ otherwise hard-to-track-down bugs could result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/597)*

**Pull request merged**
