### PR TITLE
fix for right truncation error when precision of the column definition and input is not aligned

### PR DESCRIPTION
**Pull request by v-kaywon**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/msphpsql/571)

### CODE REVIEW

**Comment by david-puglielli** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[source/shared/core_stmt.cpp, line 538 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/571#-KwvcxcItlc4SjJA942L:-KwvcxcItlc4SjJA942M:b-8gx5zq) ([raw file](https://github.com/microsoft/msphpsql/blob/94bedbe73bccf477bd4fdff63a9aeebf58a17191/source/shared/core_stmt.cpp#L538)):*
> ```cpp
>                         }
>                     }
>                     size_t precision = numDigitsBeforeDec + decimal_digits;
> ```

Where is decimal_digits defined?

---

*[test/functional/pdo_sqlsrv/pdo_decimal_precision.phpt, line 2 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/571#-KwvcHnv6E-dF1Lk3sIn:-KwvcHnv6E-dF1Lk3sIo:bk1xzlt) ([raw file](https://github.com/microsoft/msphpsql/blob/94bedbe73bccf477bd4fdff63a9aeebf58a17191/test/functional/pdo_sqlsrv/pdo_decimal_precision.phpt#L2)):*
> ```PHP
> --TEST--
> prepare with emulate prepare and binding integer
> ```

Doesn't look like the right description?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/571)*

**Comment by v-kaywon** [comment]
*[source/shared/core_stmt.cpp, line 538 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/571#-KwvcxcItlc4SjJA942L:-KwvedgFjG7EnjVj4AMQ:b-px8izv) ([raw file](https://github.com/microsoft/msphpsql/blob/94bedbe73bccf477bd4fdff63a9aeebf58a17191/source/shared/core_stmt.cpp#L538)):*
<details><summary><i>Previously, david-puglielli (David Puglielli) wrote…</i></summary><blockquote>

Where is decimal_digits defined?
</blockquote></details>

decimal_digits is defined in the bind_params function in the SQLSRV and PDO_SQLSRV side. Both sides initialize decimal_digits to 0. The actually value is retrieved by ae_get_sql_type_info, which gets the decimal_digits from calling SQLDescribeParam.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/571)*

**Comment by v-kaywon** [comment]
*[test/functional/pdo_sqlsrv/pdo_decimal_precision.phpt, line 2 at r1](https://reviewable.io:443/reviews/microsoft/msphpsql/571#-KwvcHnv6E-dF1Lk3sIn:-Kwvg85SHMuXmFjDjQvL:b-funztg) ([raw file](https://github.com/microsoft/msphpsql/blob/94bedbe73bccf477bd4fdff63a9aeebf58a17191/test/functional/pdo_sqlsrv/pdo_decimal_precision.phpt#L2)):*
<details><summary><i>Previously, david-puglielli (David Puglielli) wrote…</i></summary><blockquote>

Doesn't look like the right description?
</blockquote></details>

Yes you're right. I'll fix them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/msphpsql/571)*

**Comment by v-kaywon** [comment]
Do not merge until 5.1.1-preview is released.

**Pull request merged**
