### PR TITLE
Fix right truncation issue

### PR DESCRIPTION
**Pull request by absci**

### CODE REVIEW

**Comment by absci** [comment]
> Feel free to adopt the tests of #1404 inside this PR. Might raise codecov and also proves that the fix works. :)

I have pulled your unit test to this PR. Seems the fix is working but somehow the test throws a ```Warning: Array to string conversion in /home/vsts/work/1/s/test/functional/pdo_sqlsrv/pdo_1391_string_truncation_after_short_string.php on line 56```

**Comment by talkinnl** [comment]
@absci : My bad, fetchAll() should've been fetch()

**Comment by talkinnl** [comment]
I've updated my branch and PR. But it just comes down to replacing 'fetchAll()' by 'fetch()'.

**Comment by absci** [comment]
> I've updated my branch and PR. But it just comes down to replacing 'fetchAll()' by 'fetch()'.

Thanks, all tests passed now.

**Review by v-mabarw — APPROVED** [review]
Please separate the additional trigger into another PR.

**Comment by talkinnl** [comment]
@absci and reviewers: Thanks for the quick review and merge! 🥇 

May I ask if you've got a date set for the next fix version? Sorry if I come across a bit pushy, but I'm just excited to be a able to update a huge Doctrine project to PHP 8.1. :)

**Pull request merged**
