### PR TITLE
Add support for data type sql_variant

### LINKED ISSUE #127: PHP Fatal error:  Unexpected SQL type encountered in calc_string_size
On Linux, I get with the `sqlsrv` driver a Fatal error with following Fatal error

```
PHP Fatal error:  Unexpected SQL type encountered in calc_string_size
```

when I execute this query:

``` sql
select current_value from sys.sequences
```

The same query works well with the PDO driver `pdo_sqlsrv`.

Linux Version: Ubuntu 16.04, PHP installed as package.
PHP Version: `PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )`
`pdo_sqlsrv` `ExtensionVer => 4.0.2.0`
`sqlsrv` `ExtensionVer => 4.0.2.0`

### PR DESCRIPTION
**Pull request by xalopp**
Fixes #127

### CODE REVIEW

**Comment by meet-bhagdev** [comment]
@xalopp Thanks for the PR. We will look into this in the next few weeks.

**Comment by photodude** [comment]
@xalopp can you fix the merge conflicts here so we can try to get a PR review?

**Comment by xalopp** [comment]
@photodude sure. I added the test case which it's failling, but I'll still need to figure out, how to get my fix running again.

**Comment by Hadis-Fard** [comment]
@xalopp thanks for your contribution, closing this PR as it doesn't cover all cases that we need to add sql variant. #399 is the list of changes in order to support this feature. note that this feature is included in [4.2.0 release](https://github.com/Microsoft/msphpsql/releases/tag/v4.2.0-preview)

**Pull request closed without merging**
