### PR TITLE
Add phpize support

### LINKED ISSUE #135: Using phpize
Good afternoon!

Is it possible to compile pdo_sqlsrv with phpize on Linux?

### PR DESCRIPTION
**Pull request by xalopp**
fixes  #135

### CODE REVIEW

**Comment by meet-bhagdev** [comment]
@xalopp thanks for the PR. This looks promising. We have a quick question, what is the output of the command below after building  the drivers (using the config.m4 files in this request)?
 
```
Cd php-src-directory
Php-src-directory$ ldd ./module s/sqlsrv.so
 
```

**Comment by xalopp** [comment]
@meet-bhagdev this is the output of ldd as requested
```
ubuntu@ubuntu-xenial:/vagrant/msphpsql/source/sqlsrv$ ldd modules/sqlsrv.so 
	linux-vdso.so.1 =>  (0x00007ffe647f6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5b5659e000)
	libodbc.so.2 => /usr/local/lib/libodbc.so.2 (0x00007f5b56335000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5b5611e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5b55d55000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5b55a4c000)
	/lib64/ld-linux-x86-64.so.2 (0x0000560a8f8cb000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f5b55841000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5b55624000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5b55420000)
```

**Comment by meet-bhagdev** [comment]
Accepting the PR. Thanks a ton for your contribution @xalopp :)

**Comment by szepeviktor** [comment]
Thank you.

After installing unixodbc-2.3.1 and msodbcsql-13.0.0.0
https://github.com/Microsoft/msphpsql/wiki/Install-pdo_sqlsrv-for-PHP-7.0-on-Debian
I had several
```
In file included from /root/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv/typedefs_for_linux.h:6:0,
                 from /root/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv/winnls.h:18,
                 from /root/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv/FormattedPrint.h:18,
                 from /root/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv/core_sqlsrv.h:40,
                 from /root/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv/core_conn.cpp:20:
/root/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv/xplat.h:233:0: warning: "ODBCVER" redefined
 #define ODBCVER 0x0380
 ^
```
during make.

Then
```
# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_sqlsrv.so' - /usr/lib/php/20151012/pdo_sqlsrv.so: undefined symbol: _ZNKSt9exception4whatEv in Unknown on line 0
PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by szepeviktor** [comment]
Maybe `#ifndef` will help for the warning.

**Comment by szepeviktor** [comment]
Related: https://github.com/Microsoft/msphpsql/issues/134

**Comment by xalopp** [comment]
@szepeviktor 

The original define for `ODBCVER` is set in `/usr/include/php/20151012/main/php_config.h` (or wherever PHP installed it's includes), and PHP defaults it to `0x0300`. See [Install method 3 in the README](https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#install).

The warning can be silenced by changing the code in `xplat.h` to
```c
#if ODBCVER != 0x0380
#undef ODBCVER
#define ODBCVER 0x0380
#endif
```
but as the README points out that Version 3.52 is used by the driver, I'm not sure if this should be
```c
#if ODBCVER != 0x0352
#undef ODBCVER
#define ODBCVER 0x0352
#endif
```
@meet-bhagdev any suggestion/wishes about that? You prefer to keep the warning, or should it be silenced?

**Comment by xalopp** [comment]
@szepeviktor I can't reproduce the `undefined symbolundefined symbol` issue on Ubuntu 16.04. It seems to be specific for Debian.
Since, the PR is merged, I think you should open a new issue for that.

**Comment by szepeviktor** [comment]
> Since, the PR is merged

I've tried **this** PR.

**Comment by szepeviktor** [comment]
> Since, the PR is merged, I think you should open a new issue for that.

OK.

**Comment by szepeviktor** [comment]
@meet-bhagdev Please advise ODBCVER warnings.

**Pull request merged**
