### PR TITLE
Add instruction to Step3 for macOS users

### PR DESCRIPTION
**Pull request by satoryu**
I followed this instructions but I saw compile errors at Step 3. 
`brew info php71` gave me this instruction and it works for me :)

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/msphpsql/588)

### CODE REVIEW

**Comment by david-puglielli** [comment]
@satoryu Thank you for this pull request. I have tried the original instructions on macOS Sierra 10.12 and obtained an error in step 3, which is fixed by your additional instructions. Before I merge this PR, I would like to know: Which version of macOS are you using? Were you previously able to install the extensions without this additional step?

**Comment by satoryu** [comment]
I'm using macOS Sierra 10.12.6.
This additional instruction is set-up for pear, package manager for PHP. So if a developer have already done it, they would not need it.

**Comment by david-puglielli** [comment]
Thank you @satoryu. One more thing: please replace the link for `macOS + SQL Server + PHP 7` with this link: https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac/, for consistency with the other links in that section (it's the exact same content as the link you originally included).

**Comment by yitam** [comment]
Thank you @satoryu for your contribution.
Your pull request has been merged to the dev branch. The master branch will be updated next week.

**Pull request merged**
