### PR TITLE
Fix typo in pdo driver config.m4

### LINKED ISSUE #134: [root@localhost php.d]# php -m PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_sqlsrv.so' - /usr/lib64/php/modules/pdo_sqlsrv.so: undefined symbol: _Z10LocalAllocjj in Unknown on line 0
server :  centos7.2
php version: 7.0.9

[root@localhost php.d]# php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/php_sqlsrv_7_nts.so' - /usr/lib64/php/modules/php_sqlsrv_7_nts.so: undefined symbol: _Z9LocalFreePv in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_sqlsrv.so' - /usr/lib64/php/modules/pdo_sqlsrv.so: undefined symbol: _Z10LocalAllocjj in Unknown on line 0

why??

### PR DESCRIPTION
**Pull request by xalopp**
Fixes #134

### CODE REVIEW

**Comment by xalopp** [comment]
@szepeviktor & @PetrSpacek & @fhbzyc could you please review this PR?

```bash
cd DirectoryWhereStuffIsLocated/msphpsql/source/sqlsrv
phpize && ./configure CXXFLAGS=-std=c++11 && make && sudo make install && php -v
```

**Comment by Hadis-Fard** [comment]
@xalopp Accepted the PR, thanks for update :+1:

**Comment by szepeviktor** [comment]
Somehow #134 did not get closed.

**Comment by szepeviktor** [comment]
@xalopp it works! Thank you.

```
# php -v
PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by szepeviktor** [comment]
@meet-bhagdev Added to wiki
https://github.com/Microsoft/msphpsql/wiki/Install-pdo_sqlsrv-for-PHP-7.0-on-Debian

**Comment by xalopp** [comment]
@Hadis-Fard @szepeviktor you're welcome 😄

**Pull request merged**
